version: '3.3'
services:
  nuxt:
    image: node:20.0-alpine3.17
    command: sh -c "yarn install && yarn run dev"
    working_dir: /nuxt
    restart: always
    tmpfs: /tmp
    depends_on:
      - mysql
    environment:
      - NUXT_HOST='0.0.0.0'
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - .:/nuxt

  mysql:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: service
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql-config:/etc/mysql/conf.d