version: '3.3'
services:
  nuxt:
    image: node:20.0-alpine3.17
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"
    working_dir: /nuxt
    restart: always
    tmpfs: /tmp"
    volumes:
      - .:/nuxt