version: '3.3'
services:
  nuxt:
    image: node:20.0-alpine3.17
    command: sh -c "yarn install & yarn run dev"
    working_dir: /nuxt
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - GFC_BACKEND_API="http://localhost:3000"
      - NUXT_HOST="0.0.0.0"
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./:/nuxt

  mysql:
    image: mysql:8.1.0
    working_dir: /mysql
    environment:
      MYSQL_DATABASE: service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./:/mysql